- name: Install the Sonar
  hosts: localhost
  become: true
  tasks:
  - name: Download Java
    get_url:
      #url: http://download.oracle.com/otn-pub/java/jdk/8u60-b27/jdk-8u60-linux-x64.rpm
      url: http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.rpm
      dest: /opt/jdk-8u60-linux-x64.rpm
      #headers: 'Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie'
      headers: "Cookie: oraclelicense=accept-securebackup-cookie"
  - name: Install Java
    yum:
      name: /opt/jdk-8u60-linux-x64.rpm
      state: present
  - name: Create a Directory of Sonarinstall
    ansible.builtin.file:
      path: /opt/sonarinstall
      state: directory
      mode: '0755'    
  - name: Download and Install SonarQube Server
    get_url:
      url: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-7.8.zip
      dest: /opt/sonarinstall/sonarqube-7.8.zip
  - name: unzip the sonar zip file
    ansible.builtin.unarchive:
      src: /opt/sonarinstall/sonarqube-7.8.zip
      dest: /opt/sonarinstall
  - name: Create Sonar User
    ansible.builtin.user:
      name: sonar
      comment: Sonar user
  - name: Give the Permissions and Ownership
    ansible.builtin.file:
      path: /opt/sonarinstall
      owner: sonar
      group: sonar
      mode: '0755'
      state: directory
      recurse: yes
  - name: Start the SonarQube Service 
    become: yes
    become_user: sonar
    ansible.builtin.command:
      cmd: /opt/sonarinstall/sonarqube-7.8/bin/linux-x86-64/sonar.sh start
